// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_vim5wIl50VH3MRn22KPCrMsMgDm9xo',
    appId: '1:458185027268:web:79b35d05b14b2c5363a391',
    messagingSenderId: '458185027268',
    projectId: 'amal-157d6',
    authDomain: 'amal-157d6.firebaseapp.com',
    storageBucket: 'amal-157d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfa9H2MxjeRod5pZV7wrwdx6t4guRsLyk',
    appId: '1:458185027268:android:afbd0c94c95155f463a391',
    messagingSenderId: '458185027268',
    projectId: 'amal-157d6',
    storageBucket: 'amal-157d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBndoTsI28YxOdUydM4Wb3FcdUf9x6c3tA',
    appId: '1:458185027268:ios:95ec3d0dbec4c98163a391',
    messagingSenderId: '458185027268',
    projectId: 'amal-157d6',
    storageBucket: 'amal-157d6.firebasestorage.app',
    iosBundleId: 'com.example.amal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBndoTsI28YxOdUydM4Wb3FcdUf9x6c3tA',
    appId: '1:458185027268:ios:95ec3d0dbec4c98163a391',
    messagingSenderId: '458185027268',
    projectId: 'amal-157d6',
    storageBucket: 'amal-157d6.firebasestorage.app',
    iosBundleId: 'com.example.amal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb_vim5wIl50VH3MRn22KPCrMsMgDm9xo',
    appId: '1:458185027268:web:70f87adf95847c1363a391',
    messagingSenderId: '458185027268',
    projectId: 'amal-157d6',
    authDomain: 'amal-157d6.firebaseapp.com',
    storageBucket: 'amal-157d6.firebasestorage.app',
  );
}
